const GARMIN = {
  "atualizado": "25/09/2026 às 07:45h",
  "hoje": "2026-09-25",
  "body_battery": 7,
  "bb_max": 24,
  "bb_min": 5,
  "bb_feedback_cor": "red",
  "bb_feedback_msg": "🔴 Crítico — só recuperação hoje",
  "steps": "10.695",
  "steps_goal": "7.630",
  "steps_pct": 140,
  "steps_feedback_cor": "green",
  "steps_feedback_msg": "✅ Meta batida!",
  "fc_repouso": 65,
  "fc_feedback_cor": "green",
  "fc_feedback_msg": "✅ Saudável",
  "estresse": 52,
  "spo2_min": 90,
  "spo2_media": 95.0,
  "spo2_feedback_cor": "yellow",
  "spo2_feedback_msg": "⚡ Levemente baixo",
  "hrv_val": "--",
  "hrv_status": "--",
  "calorias_total": 803.0,
  "calorias_ativas": 404.0,
  "calorias_repouso": 399.0,
  "sono_h": 0.0,
  "sono_score": "--",
  "sono_qualidade": "--",
  "sono_profundo": 0,
  "sono_rem": 0,
  "sono_leve": 0,
  "acordou": "--",
  "spo2_sono": "--",
  "spo2_sono_min": "--",
  "sono_feedback_cor": "red",
  "sono_feedback_msg": "⚠️ Sono ruim — priorize recuperação",
  "frase_sono": "Não foi possível ler os dados de sono desta noite.",
  "orientacao_cor": "red",
  "orientacao_icon": "😴",
  "orientacao_titulo": "Dia de descanso ativo",
  "orientacao_texto": "Body Battery ou sono muito baixos. Bike leve 20–30 min · FC abaixo de 120 · Sem musculação pesada hoje.",
  "treino_nome_hoje": "Treino A — MMII Coxa completa",
  "atividade_feita": false,
  "cardio_feito": false,
  "musculacao_feita": false,
  "minutos_ativos_hoje": 0,
  "alerta_treino": "",
  "alerta_treino_urgente": false,
  "hora_brasilia": 7,
  "resumo_personal": "📋 Resumo diário — Lorena Almeida (25/09/2026 às 07:45h)\n\n🏋️ Treino do dia: Treino A — MMII Coxa completa\nMusculação: ❌ ainda não registrada\nCardio (esteira/escada): ❌ ainda não registrado\n\n⚡ Body Battery: 7/100 — 🔴 Crítico — só recuperação hoje\n😴 Sono: 0.0h · score -- — ⚠️ Sono ruim — priorize recuperação\n❤️ FC repouso: 65 bpm — ✅ Saudável\n🚶 Passos: 10695/7630 (140%) — ✅ Meta batida!\n🫁 SpO2 mínimo: 90% — ⚡ Levemente baixo\n📊 Estresse médio: 52/100\n🔋 HRV: -- (--)\n🔥 Calorias: 803.0 total (404.0 em exercício + 399.0 em repouso)\n\nOrientação automática: Dia de descanso ativo — Body Battery ou sono muito baixos. Bike leve 20–30 min · FC abaixo de 120 · Sem musculação pesada hoje.",
  "workout_agendado_data": "2026-09-25",
  "analise_diaria": "• Body Battery: 📉 de 42 para 7 (piorou em relação a ontem)\n• Sono: 📉 de 3.1 para 0.0h (piorou em relação a ontem)\n• FC repouso: 📈 de 56 para 65 bpm (piorou em relação a ontem)\n• Passos: 📈 de 7.666 para 10695 (melhorou em relação a ontem)\n• Estresse: 📈 de 17 para 52 (piorou em relação a ontem)\n• Calorias totais: 📉 de 2025.0 para 803.0 kcal (piorou em relação a ontem)",
  "ontem_snapshot": {
    "body_battery": 42,
    "sono_h": 3.1,
    "sono_score": 43,
    "fc_repouso": 56,
    "steps": "7.666",
    "estresse": 17,
    "calorias_total": 2025.0
  }
};
