const GARMIN = {
  "atualizado": "18/09/2026 às 03:54h",
  "hoje": "2026-09-18",
  "body_battery": 41,
  "bb_max": 41,
  "bb_min": 33,
  "bb_feedback_cor": "yellow",
  "bb_feedback_msg": "⚡ Moderado — cuidado na intensidade",
  "steps": "0",
  "steps_goal": "7.850",
  "steps_pct": 0,
  "steps_feedback_cor": "red",
  "steps_feedback_msg": "⚠️ Muito parada hoje",
  "fc_repouso": 65,
  "fc_feedback_cor": "green",
  "fc_feedback_msg": "✅ Saudável",
  "estresse": 17,
  "spo2_min": 91,
  "spo2_media": 96.0,
  "spo2_feedback_cor": "yellow",
  "spo2_feedback_msg": "⚡ Levemente baixo",
  "hrv_val": "--",
  "hrv_status": "--",
  "calorias_total": 81.0,
  "calorias_ativas": 0.0,
  "calorias_repouso": 81.0,
  "sono_h": 0.0,
  "sono_score": "--",
  "sono_qualidade": "--",
  "sono_profundo": 0,
  "sono_rem": 0,
  "sono_leve": 0,
  "acordou": "--",
  "spo2_sono": "--",
  "spo2_sono_min": "--",
  "sono_feedback_cor": "red",
  "sono_feedback_msg": "⚠️ Sono ruim — priorize recuperação",
  "frase_sono": "Não foi possível ler os dados de sono desta noite.",
  "orientacao_cor": "yellow",
  "orientacao_icon": "⚠️",
  "orientacao_titulo": "Treino moderado — sem forçar",
  "orientacao_texto": "Sinais de recuperação incompleta. Musculação com carga reduzida · Cardio zona 2 · Sem corrida forte hoje.",
  "treino_nome_hoje": "Treino C — MMII Glúteo e posterior",
  "atividade_feita": false,
  "cardio_feito": false,
  "musculacao_feita": false,
  "minutos_ativos_hoje": 0,
  "alerta_treino": "",
  "alerta_treino_urgente": false,
  "hora_brasilia": 3,
  "resumo_personal": "📋 Resumo diário — Lorena Almeida (18/09/2026 às 03:54h)\n\n🏋️ Treino do dia: Treino C — MMII Glúteo e posterior\nMusculação: ❌ ainda não registrada\nCardio (esteira/escada): ❌ ainda não registrado\n\n⚡ Body Battery: 41/100 — ⚡ Moderado — cuidado na intensidade\n😴 Sono: 0.0h · score -- — ⚠️ Sono ruim — priorize recuperação\n❤️ FC repouso: 65 bpm — ✅ Saudável\n🚶 Passos: 0/7850 (0%) — ⚠️ Muito parada hoje\n🫁 SpO2 mínimo: 91% — ⚡ Levemente baixo\n📊 Estresse médio: 17/100\n🔋 HRV: -- (--)\n🔥 Calorias: 81.0 total (0.0 em exercício + 81.0 em repouso)\n\nOrientação automática: Treino moderado — sem forçar — Sinais de recuperação incompleta. Musculação com carga reduzida · Cardio zona 2 · Sem corrida forte hoje.",
  "workout_agendado_data": "2026-09-18",
  "analise_diaria": "• Body Battery: 📉 de 57 para 41 (piorou em relação a ontem)\n• Sono: 📉 de 8.0 para 0.0h (piorou em relação a ontem)\n• FC repouso: 📈 de 60 para 65 bpm (piorou em relação a ontem)\n• Passos: 📉 de 9.660 para 0 (piorou em relação a ontem)\n• Estresse: 📉 de 19 para 17 (melhorou em relação a ontem)\n• Calorias totais: 📉 de 1365.0 para 81.0 kcal (piorou em relação a ontem)",
  "ontem_snapshot": {
    "body_battery": 57,
    "sono_h": 8.0,
    "sono_score": 71,
    "fc_repouso": 60,
    "steps": "9.660",
    "estresse": 19,
    "calorias_total": 1365.0
  }
};
