const GARMIN = {
  "atualizado": "05/10/2026 às 21:29h",
  "hoje": "2026-10-05",
  "body_battery": 43,
  "bb_max": 76,
  "bb_min": 23,
  "bb_feedback_cor": "yellow",
  "bb_feedback_msg": "⚡ Moderado — cuidado na intensidade",
  "steps": "3.281",
  "steps_goal": "7.080",
  "steps_pct": 46,
  "steps_feedback_cor": "yellow",
  "steps_feedback_msg": "⚡ Continue se movendo",
  "fc_repouso": 60,
  "fc_feedback_cor": "green",
  "fc_feedback_msg": "✅ Saudável",
  "estresse": 27,
  "spo2_min": "--",
  "spo2_media": "--",
  "spo2_feedback_cor": "green",
  "spo2_feedback_msg": "✅ Normal",
  "hrv_val": 42,
  "hrv_status": "BALANCED",
  "calorias_total": 1629.0,
  "calorias_ativas": 348.0,
  "calorias_repouso": 1281.0,
  "sono_h": 6.7,
  "sono_score": 81,
  "sono_qualidade": "GOOD",
  "sono_profundo": 73,
  "sono_rem": 94,
  "sono_leve": 235,
  "acordou": 1,
  "spo2_sono": "--",
  "spo2_sono_min": "--",
  "sono_feedback_cor": "green",
  "sono_feedback_msg": "✅ Sono bom",
  "frase_sono": "Boa noite de sono! Você dormiu 6.7h com score 81 — seu corpo recuperou bem. Aproveite o dia.",
  "orientacao_cor": "yellow",
  "orientacao_icon": "⚠️",
  "orientacao_titulo": "Treino moderado — sem forçar",
  "orientacao_texto": "Sinais de recuperação incompleta. Musculação com carga reduzida · Cardio zona 2 · Sem corrida forte hoje.",
  "treino_nome_hoje": "Treino A — MMII Coxa completa",
  "atividade_feita": true,
  "cardio_feito": false,
  "musculacao_feita": true,
  "minutos_ativos_hoje": 37,
  "alerta_treino": "",
  "alerta_treino_urgente": false,
  "hora_brasilia": 21,
  "resumo_personal": "📋 Resumo diário — Lorena Almeida (05/10/2026 às 21:29h)\n\n🏋️ Treino do dia: Treino A — MMII Coxa completa\nMusculação: ✅ feita\nCardio (esteira/escada): ❌ ainda não registrado — 37 min de atividade hoje\n\n⚡ Body Battery: 43/100 — ⚡ Moderado — cuidado na intensidade\n😴 Sono: 6.7h · score 81 — ✅ Sono bom\n❤️ FC repouso: 60 bpm — ✅ Saudável\n🚶 Passos: 3281/7080 (46%) — ⚡ Continue se movendo\n🫁 SpO2 mínimo: --% — ✅ Normal\n📊 Estresse médio: 27/100\n🔋 HRV: 42 (BALANCED)\n🔥 Calorias: 1629.0 total (348.0 em exercício + 1281.0 em repouso)\n\nOrientação automática: Treino moderado — sem forçar — Sinais de recuperação incompleta. Musculação com carga reduzida · Cardio zona 2 · Sem corrida forte hoje.",
  "workout_agendado_data": "2026-10-05",
  "analise_diaria": "• Body Battery: 📈 de 24 para 43 (melhorou em relação a ontem)\n• Sono: estável em 6.7h\n• Score do sono: 📈 de 72 para 81 (melhorou em relação a ontem)\n• FC repouso: estável em 60 bpm\n• Passos: 📈 de 5.866 para 3281 (melhorou em relação a ontem)\n• Estresse: 📉 de 34 para 27 (melhorou em relação a ontem)\n• Calorias totais: 📉 de 2203.0 para 1629.0 kcal (piorou em relação a ontem)",
  "ontem_snapshot": {
    "body_battery": 24,
    "sono_h": 6.7,
    "sono_score": 72,
    "fc_repouso": 60,
    "steps": "5.866",
    "estresse": 34,
    "calorias_total": 2203.0
  }
};
